version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin  
      RABBITMQ_DEFAULT_PASS: admin

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: pguser  
      POSTGRES_PASSWORD: pgpassword 
      POSTGRES_DB: subscriber_db  
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
